default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PWD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
